# Create a workflow that truggers nabually and:
# 1. print our sloga
# 2. Guess our magic number
name: Secet stuff
on: workflow_dispatch

jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
  
    steps:
    - run: echo ${{ vars.SLOGAN}}
    - run: echo $SLOGAN
    
  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
    steps:
      - name: Guess magic number
        run: echo $MAGIC_NUMBER
      - name: gues with environment variable
        run: echo ${{ secrets.MY_MAGIC_NUMBER }}
        

  print_and_guess:
    runs-on: ubuntu-latest

    env:
      SLOGAN: ${{ secrets.SLOGAN }}
      MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
      
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4
  
        
      - name: Start SSH session
        uses: mxschmitt/action-tmate@v3
      
            
      - name: Display Instructions
        run: |
          echo "SSH session started. Use the SSH command provided in the logs to connect."
          echo "Once connected, use 'echo $MY_MAGIC_NUMBER' to view the unmasked number."
                  
                  
            
    
