# Create a workflow that truggers nabually and:
# 1. print our sloga
# 2. Guess our magic number
name: Secet stuff
on: workflow_dispatch

jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
  
    steps:
    - run: echo ${{ vars.SLOGAN}}
    - run: echo $SLOGAN
  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
    steps:
      - name: Guess magic number
        run: echo $MY_MAGIC_NUMBER
      - name: gues with environment variable
        run: echo ${{ secrets.MY_MAGIC_NUMBER }}
  append-slogan-and-number:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
      MY_MAGIC_NUMBER: ${{ vars.MY_MAGIC_NUMBER }}

    steps:
    - name: Append
      run: echo "Slogan =${SLOGAN} - Magic number${MY_MAGIC_NUMBER}" >> $GITHUB_ENV
    - name: new slogam
      run: echo $SLOGAN
            
          
          
  
