# Create a workflow that truggers nabually and:
# 1. print our sloga
# 2. Guess our magic number
name: Secet stuff
on: workflow_dispatch

jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: ${{ vars.SLOGAN }}
  
    steps:
    - run: echo ${{ vars.SLOGAN}}
    - run: echo $SLOGAN
    
  guess-magic-number:
    runs-on: ubuntu-latest
    env:
      MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
    steps:
      - name: Guess magic number
        run: echo $MY_MAGIC_NUMBER
      - name: gues with environment variable
        run: echo ${{ secrets.MY_MAGIC_NUMBER }}
        

  print_and_guess:
    runs-on: ubuntu-latest

    env:
        SLOGAN: ${{ secrets.SLOGAN }}
        MY_MAGIC_NUMBER: ${{ secrets.MY_MAGIC_NUMBER }}
        ACTIONS_STEP_DEBUG: true  # Enable debug mode
  
    steps:
    - name: Print Slogan and Magic Number
      run: |
            echo "SLOGAN: $SLOGAN"
            echo "MAGIC_NUMBER: $MY_MAGIC_NUMBER"
                      
                    
              
    
