# Create a workflow that truggers nabually and:
# 1. print our sloga
# 2. Guess our magic number
name: Secet stuff
on: workflow_dispatch

jobs:
  print-slogan:
    runs-on: ubuntu-latest

    env:
      SLOGAN: ${{ vars.SLOGAN }}
      MAGIC_NUMBER: ${{ secrets.MAGIC_NUMBER }}
  
    steps:
    - name: Print Slogan
    - run: echo ${{ vars.SLOGAN}}
    - run: echo $SLOGAN
    - name: Magic number
      run: | 
        echo "Magic number $MAGIC_NUMBER"
        echo "Magic number ${{ secrets.MAGIC_NUMBER }}"
          
          
  
