# Create a workflow that truggers nabually and:
# 1. print our sloga
# 2. Guess our magic number
name: Secet stuff
on: workflow_dispatch

jobs:
  print-slogan:
    runs-on: ubuntu-latest

    env:
      SLOGAN: ${{ secrets.SLOGAN }}
      MAGIC_NUMBER: ${{ secrets.MAGIC_NUMBER }}
  
    steps:
    - name: Print Slogan
      run: echo " our slogan $SLOGAN"
    - name: Magic number
      run: | 
        echo "Magic number $MAGIC_NUMBER"
          
          
  
